name: C/C++ CI

on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
       cmake \
       --no-warn-unused-cli \
       -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
       -DCMAKE_BUILD_TYPE:STRING=Debug \
       -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang \
       -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ \
       -DWITH_TEST=1 \
       -H$GITHUB_WORKSPACE \
       -B$GITHUB_WORKSPACE/build
        
    - name: cmake build
      run: |
       cmake \
       --build $GITHUB_WORKSPACE/build \
       --config Debug \
       --target all \
       -- \
       -j 10

    - name: run tests
      run: $GITHUB_WORKSPACE/build/test/unittest
